AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM application template for Verifier Certificate Authority backend

Parameters:
  Environment:
    Description: The environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - prod

  CodeSigningConfigArn:
    Description: |
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Type: String
    Default: none

  PermissionsBoundary:
    Description: |
      The ARN of the permissions boundary to apply to any role created by the template
    Type: String
    Default: none

  VpcStackName:
    Description: |
      The stack name of the VPC where Verifier CA lambdas will be deployed
    Type: String
    Default: vpc

  CaBackendApiParam:
    Description: |
      The backend Api prefix url
    Type: String
    Default: ca-backend-api

  CloudFrontDistributionName:
    Description: |
      The name of the CloudFront distribution
    Type: String
    Default: cloudfront-distribution

Conditions:
  EgressLogsToSplunkUsingCsls: !Or
    - !Equals
      - !Ref Environment
      - staging
    - !Equals
      - !Ref Environment
      - integration
    - !Equals
      - !Ref Environment
      - production

  UsePermissionsBoundary: !Not
    - !Equals
      - !Ref PermissionsBoundary
      - none

  UseCodeSigning: !Not
    - !Equals
      - !Ref CodeSigningConfigArn
      - none

Mappings:
  EnvironmentVariables:
    dev:
      LambdaLogLevel: DEBUG
      DynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables

    build:
      LambdaLogLevel: INFO
      DynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables

    CslsEgress:
      build: arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython-2
      integration: arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython-2
      production: arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython-2
      staging: arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython-2

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: !FindInMap
        - EnvironmentVariables
        - !Ref Environment
        - LambdaLogLevel
      SystemLogLevel: !FindInMap
        - EnvironmentVariables
        - !Ref Environment
        - LambdaLogLevel
    Runtime: nodejs22.x
    Architectures:
      - arm64
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    AutoPublishAlias: live
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    Environment:
      Variables:
        DT_CONNECTION_AUTH_TOKEN: !Sub
          - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_AUTH_TOKEN}}'
          - SecretArn: !FindInMap
              - EnvironmentVariables
              - !Ref Environment
              - DynatraceSecretArn
        DT_CONNECTION_BASE_URL: !Sub
          - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_BASE_URL}}'
          - SecretArn: !FindInMap
              - EnvironmentVariables
              - !Ref Environment
              - DynatraceSecretArn
        DT_CLUSTER_ID: !Sub
          - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CLUSTER_ID}}'
          - SecretArn: !FindInMap
              - EnvironmentVariables
              - !Ref Environment
              - DynatraceSecretArn
        DT_LOG_COLLECTION_AUTH_TOKEN: !Sub
          - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_LOG_COLLECTION_AUTH_TOKEN}}'
          - SecretArn: !FindInMap
              - EnvironmentVariables
              - !Ref Environment
              - DynatraceSecretArn
        DT_TENANT: !Sub
          - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_TENANT}}'
          - SecretArn: !FindInMap
              - EnvironmentVariables
              - !Ref Environment
              - DynatraceSecretArn
        DT_OPEN_TELEMETRY_ENABLE_INTEGRATION: 'true'
    Layers:
      - arn:aws:lambda:eu-west-2:216552277552:layer:Dynatrace_OneAgent_1_311_2_20250307-045250_with_collector_nodejs:1

Resources:
  NonceServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-${Environment}-nonce-service-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                Resource: !Sub
                  - 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}'
                  - TableName:
                      Fn::ImportValue: !Sub '${Environment}-NonceTableName'

  NonceServiceFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Sourcemap: false
        Target: es2022
    Properties:
      FunctionName: !Sub '${AWS::StackName}-${Environment}-nonce-service'
      CodeUri: ./
      Handler: src/lambdas/nonce-service/handler.handler
      Role: !GetAtt NonceServiceRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-AWSServicesEndpointSecurityGroupId
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdA
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdB
          - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdC
      Environment:
        Variables:
          NONCE_TABLE_NAME:
            Fn::ImportValue: !Sub '${Environment}-NonceTableName'

  NonceServiceFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AWS::StackName}-nonce-service
      RetentionInDays: 30

  NonceServiceFunctionSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !FindInMap
        - EnvironmentVariables
        - CslsEgress
        - !Ref Environment
      FilterPattern: ''
      LogGroupName: !Ref NonceServiceFunctionLogGroup
    Condition: EgressLogsToSplunkUsingCsls

  CaBackendApi:
    Type: AWS::Serverless::Api
    DependsOn: ApiGatewayAccount
    Properties:
      Name: !Sub ${AWS::StackName}-${CaBackendApiParam}
      Description: Regional API gateway for the verifier certificate authority service
      StageName: !Ref Environment
      OpenApiVersion: 3.0.0
      TracingEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt CaBackendApiAccessLogs.Arn
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "caller":"$context.identity.caller", "user":"$context.identity.user","requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath", "status":"$context.status","protocol":"$context.protocol", "responseLength":"$context.responseLength" }'
      EndpointConfiguration:
        Type: REGIONAL
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: /*
          HttpMethod: '*'
          DataTraceEnabled: false
          MetricsEnabled: true
          ThrottlingBurstLimit: 10
          ThrottlingRateLimit: 10
          CachingEnabled: true
          CacheTtlInSeconds: 300
          CacheDataEncrypted: true
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./open-api-spec.yaml

  CaBackendApiAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${AWS::StackName}-${CaBackendApiParam}-access-logs
      RetentionInDays: 30

  NonceServicePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref NonceServiceFunction.Alias
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${CaBackendApi}/*/*'

  ApiGatewayCloudWatchLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ApiGatewayLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                  - logs:GetLogEvents
                  - logs:FilterLogEvents
                Resource: '*'

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchLogsRole.Arn

  # CaBackendApiWebAclAssociation:
  #   Type: AWS::WAFv2::WebACLAssociation
  #   Properties:
  #     ResourceArn: !Sub
  #       - 'arn:aws:apigateway:${AWS::Region}::/restapis/${CaBackendApi}/stages/${ApiStage}'
  #       - ApiStage: !Ref CaBackendApi.Stage
  #     WebACLArn:
  #       Fn::ImportValue: !Sub '${CloudFrontDistributionName}-CloakingOriginWebACLArn'

Outputs:
  ApiGatewayDomainName:
    Description: API Gateway regional domain name for CloudFront origin
    Value: !Sub 'https://${CaBackendApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-api-url'

  ApiGatewayId:
    Description: API Gateway ID
    Value: !Ref CaBackendApi
    Export:
      Name: !Sub '${AWS::StackName}-api-id'

  ApiStage:
    Description: API Gateway deployment stage
    Value: !Ref Environment
    Export:
      Name: !Sub '${AWS::StackName}-api-stage'
