name: Validate Base Application Infrastructure

on:
  workflow_call:
    inputs:
      AWS_REGION:
        description: The AWS region
        type: string
        default: eu-west-2
      TEMPLATE_PATH:
        description: Path to the SAM template
        type: string
        default: base-application.yaml

jobs:
  validate:
    name: 'Validate SAM Template'
    runs-on: ubuntu-24.04
    env:
      SAM_CLI_TELEMETRY: 0
      TEMPLATE_PATH: ${{ inputs.TEMPLATE_PATH }}
      AWS_REGION: ${{ inputs.AWS_REGION }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref }}
          submodules: true

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@c2a20b1822cc4a6bc594ff7f1dbb658758e383c3 # v2

      - name: SAM Validate
        run: |
          sam validate --lint --template "$TEMPLATE_PATH" --region "$AWS_REGION"

      - name: Run cfn-lint
        run: |
          pip install cfn-lint
          cfn-lint "$TEMPLATE_PATH"
