name: Validate, Build, and Upload Artifact to S3

on:
  workflow_call:
    inputs:
      AWS_REGION:
        description: The AWS region
        type: string
        default: eu-west-2
      TEMPLATE_NAME:
        description: The name of the SAM template to upload
        type: string
        default: application.yaml
      WORKING_DIRECTORY:
        description: Path to working directory in repo
        required: true
        type: string
    secrets:
      ARTIFACT_BUCKET:
        description: Artifact source bucket for SAM artifact
        required: true
      GH_ACTIONS_ROLE_ARN:
        description: AWS role for pushing the test image and AWS artifact to AWS
        required: true
      SIGNING_PROFILE_NAME:
        description: Profile used to sign SAM artifact
        required: true

jobs:
  upload-artifact:
    name: 'Validate and Upload Artifact'
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
    env:
      SAM_CLI_TELEMETRY: 0
      TEMPLATE_NAME: ${{ inputs.TEMPLATE_NAME }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref }}
          submodules: true
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version-file: .nvmrc

      - name: Configure Authentication for Private Packages in .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "engine-strict=true" > .npmrc
          echo "@govuk-one-login:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc

      - name: Install Dependencies
        run: npm clean-install

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 #v5.1.1
        with:
          aws-region: ${{ inputs.AWS_REGION }}
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}

      - name: SAM Validate
        run: sam validate --lint --template "$TEMPLATE_NAME"

      - name: SAM Build
        run: sam build --cached --template "$TEMPLATE_NAME"

      - name: Upload SAM Artifact into the Artifact Bucket
        uses: govuk-one-login/devplatform-upload-action@abbf25e43a88b3512b1a43621f9aef4cbea1b648 # v3.12.1
        with:
          artifact-bucket-name: ${{ secrets.ARTIFACT_BUCKET }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          template-file: .aws-sam/build/template.yaml
